version: "3.9"
services:
  
  postgres:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
    ports:
      - 5432:5432

  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379

  app:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
